name: mopoe
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - matplotlib=3.4.3
  - numpy=1.23.3
  - pandas=1.4.4
  - python=3.9.13
  - pytorch=1.13.0
  - scikit-learn=1.0.2
  - scipy=1.9.3
  - tensorboardx=1.9.3
  - tensorboard
  - torchvision=0.14.0
  - fire
  - iterative-stratification
  - plotly
  - kaleido
  - statsmodels
