#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob globstar

# define TMPDIR, if it's empty
if [[ -z "$TMPDIR" ]]; then
    TMPDIR="/tmp"
fi
echo "TMPDIR: $TMPDIR"

# activate conda env
#eval "$(conda shell.bash hook)"
#conda activate mopoe
#echo "CONDA_PREFIX: $CONDA_PREFIX"
# n_epochs euaim : 1500
# n_epochs hbn with missing : 550

METHOD="joint_elbo"  # NOTE: valid options are "joint_elbo", "poe", and "moe"
LIKELIHOOD="normal"

cd experiments_results_figures/

python main.py \
            --dataset="$DATASET" \
            --datasetdir="$DATASETDIR" \
            --dir_experiment="$DIR_EXPERIMENT" \
            --method=$METHOD \
            --style_dim 3 20 \
            --class_dim=20 \
            --input_dim 7 444 \
            --beta=1 \
            --likelihood=$LIKELIHOOD \
            --batch_size=256 \
            --initial_learning_rate=0.002 \
            --eval_freq=25 \
            --eval_freq_fid=100 \
            --data_multiplications=1 \
            --num_hidden_layer_encoder=1 \
            --num_hidden_layer_decoder=0 \
            --end_epoch=550 \
            -dr 0.0 \
            --initial_out_logvar=-3 \
            --learn_output_scale \
            --factorized_representation \
            --allow_missing_blocks \
            # --learn_output_sample_scale \

            # --dir_fid="$DIR_FID" \
            # --inception_state_dict="$PATH_INC_V3" \
            
            #--kl_annealing 500