#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob globstar

# define TMPDIR, if it's empty
if [[ -z "$TMPDIR" ]]; then
    TMPDIR="/tmp"
fi
echo "TMPDIR: $TMPDIR"

# activate conda env
#eval "$(conda shell.bash hook)"
#conda activate mopoe
#echo "CONDA_PREFIX: $CONDA_PREFIX"

METHOD="joint_elbo"  # NOTE: valid options are "joint_elbo", "poe", and "moe"
LIKELIHOOD="normal"

cd MoPoE/

python main.py \
            --dataset="$DATASET" \
            --datasetdir="$DATASETDIR" \
            --dir_experiment="$DIR_EXPERIMENT" \
            --method=$METHOD \
            --style_dim=0 \
            --class_dim=20 \
            --input_dim 7 444 \
            --beta="$((5))" \
            --likelihood=$LIKELIHOOD \
            --batch_size=256 \
            --initial_learning_rate=0.002 \
            --eval_freq=25 \
            --eval_freq_fid=100 \
            --data_multiplications=1 \
            --num_hidden_layers=1 \
            --end_epoch=2500 \
            -dr 0.0 \
            --initial_out_logvar=-3 \
            --learn_output_scale \
            --allow_missing_blocks
            # --dir_fid="$DIR_FID" \
            # --inception_state_dict="$PATH_INC_V3" \
            # --factorized_representation
            #--kl_annealing 500